In [ ]:
#Name:- Sayee Deshmukh
#Roll No:- 34
#Batch:- T2
#Assignment Title:- 

In [5]:
#import numpy library
import numpy as np

In [48]:
#Array attributes

# 1 dimensional array
arr=np.array([1,2,3,4]);
print("Array:- ",arr);
print("Dimensions:- ",arr.ndim);
print("Size of the array:- ",arr.size);
print("Shape of the array:- ",arr.shape);
print("Maximum value in array:- ",np.max(arr));
print("Maximum value in array:- ",np.min(arr));
print("Reshaping the array:- \n",arr.reshape(2,2));

print("\n");

# 2 dimensional array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]]);
print("Array:-\n",arr2);
print("Dimensions of the array:- ",arr2.ndim);
print("Size of the array:- ",arr2.size);
print("Shape of the array:- ",arr2.shape);
print("Maximum value in array:- ",np.max(arr2));
print("Maximum value in array:- ",np.min(arr2));
print("Reshaping the array:- \n",arr2.reshape(9,1));
print("Reshaping the array:- \n",arr2.reshape(9));
print("Reshaping the array:- \n",arr2.reshape(3,3,1));
print("Reshaping the array:- \n",arr2.reshape(3,1,3));


Array:-  [1 2 3 4]
Dimensions:-  1
Size of the array:-  4
Shape of the array:-  (4,)
Maximum value in array:-  4
Maximum value in array:-  1
Reshaping the array:- 
 [[1 2]
 [3 4]]


Array:-
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensions of the array:-  2
Size of the array:-  9
Shape of the array:-  (3, 3)
Maximum value in array:-  9
Maximum value in array:-  1
Reshaping the array:- 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Reshaping the array:- 
 [1 2 3 4 5 6 7 8 9]
Reshaping the array:- 
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
Reshaping the array:- 
 [[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [58]:
#Array Indexing of 1D array
print(arr[1]);
print(arr[-1]);
print(arr[:3]);
print

print("\n");

#Array indexing of 2D array
print(arr2[0,0]);
print(arr2[-1,0]);



2
4
[1 2 3]


1
7
