In [67]:
#print datatype of array and change its datatype and print again 

import numpy as np
arr = np.zeros(10);
print(arr);
print(arr.dtype);
arr = np.zeros(10,dtype=int);
print(arr);
print(arr.dtype);


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[0 0 0 0 0 0 0 0 0 0]
int32


In [62]:
arr=np.array([(1,2,3,8),(1,2,3,49),(1,2,3,4)]);
print(arr);
print("shape of array is:-" ,arr.shape);
print("dimensions of the array is:-", arr.ndim)

[[ 1  2  3  8]
 [ 1  2  3 49]
 [ 1  2  3  4]]
shape of array is:- (3, 4)
dimensions of the array is:- 2


In [59]:
#swap function 

swap=np.swapaxes(arr,0,1);
print("swapped array is:- \n",swap);

swapped array is:- 
 [[ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]
 [ 8 49  4]]


In [60]:
#max function 

maximum=arr.max();
print(maximum);

49


In [61]:
#reshape function

reshape=arr.reshape(4,3);
print(reshape);

[[ 1  2  3]
 [ 8  1  2]
 [ 3 49  1]
 [ 2  3  4]]


In [64]:
#linspace function

lines=arr.linspace()
print(lines);

AttributeError: 'numpy.ndarray' object has no attribute 'linspace'

In [ ]:
#sort(axis=0 and axis=1)

